### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by KuldeepBorkar** [eagleoflqj/sympy_beta#4]
## Input
`2*sin(x) + 3*cos(x)`
## How can it be better?
I tried using `sympy_beta` and it truly is great but if we could use say above equation like this `2sin(x) + 3cos(x)` i.e. without `*` symbol for multiplication then it would be more efficient just like we give inputs in `Wolfram|Alpha` currently it would say `invalid syntax`.

I don't know if this feature could be added but thought I should try mentioning it.

**Comment by eagleoflqj** [comment]
Yes. Parsing should definitely be improved. SymPy Gamma handles it correctly. I disabled implicit multiplication causes confusion, like https://sympygamma.com/input/?i=velocity.
But `2sin(x)+3cos(x)` is a different case. I'll do it.

**Comment by eagleoflqj** [comment]
Fixed at f05f33ca8737ae90590c6b2a0bc1604ab3155dfd
A bit harder than I thought. I have to use a vocabulary from nltk, and copy-modify sympy code.
There are a ton of items in my todo list. So, thanks for letting me make up my mind prioritize this.

**Comment by KuldeepBorkar** [comment]
Thanks, I hope it would have not caused any errors in the code.
I will learn more and soon try to contribute here too : )

**Comment by eagleoflqj** [comment]
> I hope it would have not caused any errors in the code.

It does, just like any kinds of fix. But I believe if something is broken and we fail to notice immediately, that just indicates we need better test coverage.

> I will learn more and soon try to contribute here too : )

Appreciated! I've write a piece of [doc](https://github.com/eagleoflqj/sympy_beta/tree/master/doc). Feel free to provide opinions and I'll make it clearer.
